query {
  searchFulltext(
    query: "[QUERY]"
    order: { sorting: RELEVANCE, sortingDiretion: DESC }
    filter: { discardSelfpublished: false, typesAllowed: [Anime, GraphicNovel] }
    first: 10
    offset: 0
  ) {
    resultTotal
    results {
      ... on GraphGeneric {
        entityType
        name
        names {
          text
          localizationTag
        }
      }
      ... on GraphContent {
        publishingType
        original
        status
        releaseDate {
          year
          month
          day
        }
      }
    }
  }
}
