query {
  viewer {
    trackers(pageSize: 10) {
      nextPageToken
      trackers {
        name
        completedResources {
          ... on GraphGeneric {
            name
          }
        }
        progressPercentage

        resource {
          ... on GraphGeneric {
            name
          }
        }
      }
    }
  }
}
