query {
  getGraphGeneric(name: "[RESOURCE-NAME]") {
    name
    ... on GraphContent {
      relations {
        type
        object {
          name
          ... on GraphGeneric {
            names {
              text
              localizationTag
            }
          }
        }
      }
    }
  }
}
